// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TransformEnemyByState","status":true,"description":"Временно превращает врага в другого врага через состояние.","parameters":{}},
{"name":"RandomSplash","status":true,"description":"Показывает случайную картинку из img/splash вместо Made with MV.","parameters":{"Fade In Time":"60","Wait Time":"120","Fade Out Time":"60","Fallback Images":""}},
{"name":"Dota2Quiz","status":true,"description":"Dota 2 Quiz: 10 questions, 15 sec timer, gold rewards + result variable.","parameters":{"Questions Per Game":"15","Time Limit":"15","Gold Correct":"150","Gold Wrong":"350","Result Variable ID":"30"}},
{"name":"PSV","status":true,"description":"Просмотр эффектов партии в бою (v12). R / кнопка \"Эффекты\".","parameters":{}},
{"name":"EnemyHPViewer","status":true,"description":"Полоса HP под ВИДИМОЙ частью изображения врага + мелкие цифры.","parameters":{"Bar Width":"100","Y Offset":"0"}}
];
